//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Astros.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cardsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cardsEntities object using the connection string found in the 'cardsEntities' section of the application configuration file.
        /// </summary>
        public cardsEntities() : base("name=cardsEntities", "cardsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cardsEntities object.
        /// </summary>
        public cardsEntities(string connectionString) : base(connectionString, "cardsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cardsEntities object.
        /// </summary>
        public cardsEntities(EntityConnection connection) : base(connection, "cardsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player_stats> player_stats
        {
            get
            {
                if ((_player_stats == null))
                {
                    _player_stats = base.CreateObjectSet<player_stats>("player_stats");
                }
                return _player_stats;
            }
        }
        private ObjectSet<player_stats> _player_stats;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player> players
        {
            get
            {
                if ((_players == null))
                {
                    _players = base.CreateObjectSet<player>("players");
                }
                return _players;
            }
        }
        private ObjectSet<player> _players;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the player_stats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayer_stats(player_stats player_stats)
        {
            base.AddObject("player_stats", player_stats);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayers(player player)
        {
            base.AddObject("players", player);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cardsModel", Name="player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player object.
        /// </summary>
        /// <param name="player_id">Initial value of the player_id property.</param>
        public static player Createplayer(global::System.Int32 player_id)
        {
            player player = new player();
            player.player_id = player_id;
            return player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 player_id
        {
            get
            {
                return _player_id;
            }
            set
            {
                if (_player_id != value)
                {
                    Onplayer_idChanging(value);
                    ReportPropertyChanging("player_id");
                    _player_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("player_id");
                    Onplayer_idChanged();
                }
            }
        }
        private global::System.Int32 _player_id;
        partial void Onplayer_idChanging(global::System.Int32 value);
        partial void Onplayer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String player_name
        {
            get
            {
                return _player_name;
            }
            set
            {
                Onplayer_nameChanging(value);
                ReportPropertyChanging("player_name");
                _player_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("player_name");
                Onplayer_nameChanged();
            }
        }
        private global::System.String _player_name;
        partial void Onplayer_nameChanging(global::System.String value);
        partial void Onplayer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uniform_number
        {
            get
            {
                return _uniform_number;
            }
            set
            {
                Onuniform_numberChanging(value);
                ReportPropertyChanging("uniform_number");
                _uniform_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uniform_number");
                Onuniform_numberChanged();
            }
        }
        private Nullable<global::System.Int32> _uniform_number;
        partial void Onuniform_numberChanging(Nullable<global::System.Int32> value);
        partial void Onuniform_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bats
        {
            get
            {
                return _bats;
            }
            set
            {
                OnbatsChanging(value);
                ReportPropertyChanging("bats");
                _bats = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bats");
                OnbatsChanged();
            }
        }
        private global::System.String _bats;
        partial void OnbatsChanging(global::System.String value);
        partial void OnbatsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String throws
        {
            get
            {
                return _throws;
            }
            set
            {
                OnthrowsChanging(value);
                ReportPropertyChanging("throws");
                _throws = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("throws");
                OnthrowsChanged();
            }
        }
        private global::System.String _throws;
        partial void OnthrowsChanging(global::System.String value);
        partial void OnthrowsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> height
        {
            get
            {
                return _height;
            }
            set
            {
                OnheightChanging(value);
                ReportPropertyChanging("height");
                _height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("height");
                OnheightChanged();
            }
        }
        private Nullable<global::System.Int32> _height;
        partial void OnheightChanging(Nullable<global::System.Int32> value);
        partial void OnheightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private Nullable<global::System.Int32> _weight;
        partial void OnweightChanging(Nullable<global::System.Int32> value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String birth_date
        {
            get
            {
                return _birth_date;
            }
            set
            {
                Onbirth_dateChanging(value);
                ReportPropertyChanging("birth_date");
                _birth_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("birth_date");
                Onbirth_dateChanged();
            }
        }
        private global::System.String _birth_date;
        partial void Onbirth_dateChanging(global::System.String value);
        partial void Onbirth_dateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cardsModel", Name="player_stats")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player_stats : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player_stats object.
        /// </summary>
        /// <param name="player_id">Initial value of the player_id property.</param>
        /// <param name="bat_side">Initial value of the bat_side property.</param>
        /// <param name="count_balls">Initial value of the count_balls property.</param>
        /// <param name="count_strikes">Initial value of the count_strikes property.</param>
        /// <param name="pitch_type">Initial value of the pitch_type property.</param>
        public static player_stats Createplayer_stats(global::System.Int32 player_id, global::System.String bat_side, global::System.Int32 count_balls, global::System.Int32 count_strikes, global::System.String pitch_type)
        {
            player_stats player_stats = new player_stats();
            player_stats.player_id = player_id;
            player_stats.bat_side = bat_side;
            player_stats.count_balls = count_balls;
            player_stats.count_strikes = count_strikes;
            player_stats.pitch_type = pitch_type;
            return player_stats;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 player_id
        {
            get
            {
                return _player_id;
            }
            set
            {
                if (_player_id != value)
                {
                    Onplayer_idChanging(value);
                    ReportPropertyChanging("player_id");
                    _player_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("player_id");
                    Onplayer_idChanged();
                }
            }
        }
        private global::System.Int32 _player_id;
        partial void Onplayer_idChanging(global::System.Int32 value);
        partial void Onplayer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bat_side
        {
            get
            {
                return _bat_side;
            }
            set
            {
                if (_bat_side != value)
                {
                    Onbat_sideChanging(value);
                    ReportPropertyChanging("bat_side");
                    _bat_side = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("bat_side");
                    Onbat_sideChanged();
                }
            }
        }
        private global::System.String _bat_side;
        partial void Onbat_sideChanging(global::System.String value);
        partial void Onbat_sideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count_balls
        {
            get
            {
                return _count_balls;
            }
            set
            {
                if (_count_balls != value)
                {
                    Oncount_ballsChanging(value);
                    ReportPropertyChanging("count_balls");
                    _count_balls = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("count_balls");
                    Oncount_ballsChanged();
                }
            }
        }
        private global::System.Int32 _count_balls;
        partial void Oncount_ballsChanging(global::System.Int32 value);
        partial void Oncount_ballsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count_strikes
        {
            get
            {
                return _count_strikes;
            }
            set
            {
                if (_count_strikes != value)
                {
                    Oncount_strikesChanging(value);
                    ReportPropertyChanging("count_strikes");
                    _count_strikes = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("count_strikes");
                    Oncount_strikesChanged();
                }
            }
        }
        private global::System.Int32 _count_strikes;
        partial void Oncount_strikesChanging(global::System.Int32 value);
        partial void Oncount_strikesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pitch_type
        {
            get
            {
                return _pitch_type;
            }
            set
            {
                if (_pitch_type != value)
                {
                    Onpitch_typeChanging(value);
                    ReportPropertyChanging("pitch_type");
                    _pitch_type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("pitch_type");
                    Onpitch_typeChanged();
                }
            }
        }
        private global::System.String _pitch_type;
        partial void Onpitch_typeChanging(global::System.String value);
        partial void Onpitch_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_pitches
        {
            get
            {
                return _num_pitches;
            }
            set
            {
                Onnum_pitchesChanging(value);
                ReportPropertyChanging("num_pitches");
                _num_pitches = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_pitches");
                Onnum_pitchesChanged();
            }
        }
        private Nullable<global::System.Int32> _num_pitches;
        partial void Onnum_pitchesChanging(Nullable<global::System.Int32> value);
        partial void Onnum_pitchesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_balls
        {
            get
            {
                return _num_balls;
            }
            set
            {
                Onnum_ballsChanging(value);
                ReportPropertyChanging("num_balls");
                _num_balls = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_balls");
                Onnum_ballsChanged();
            }
        }
        private Nullable<global::System.Int32> _num_balls;
        partial void Onnum_ballsChanging(Nullable<global::System.Int32> value);
        partial void Onnum_ballsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num_strikes
        {
            get
            {
                return _num_strikes;
            }
            set
            {
                Onnum_strikesChanging(value);
                ReportPropertyChanging("num_strikes");
                _num_strikes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num_strikes");
                Onnum_strikesChanged();
            }
        }
        private Nullable<global::System.Int32> _num_strikes;
        partial void Onnum_strikesChanging(Nullable<global::System.Int32> value);
        partial void Onnum_strikesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avg_speed
        {
            get
            {
                return _avg_speed;
            }
            set
            {
                Onavg_speedChanging(value);
                ReportPropertyChanging("avg_speed");
                _avg_speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avg_speed");
                Onavg_speedChanged();
            }
        }
        private Nullable<global::System.Decimal> _avg_speed;
        partial void Onavg_speedChanging(Nullable<global::System.Decimal> value);
        partial void Onavg_speedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avg_spin
        {
            get
            {
                return _avg_spin;
            }
            set
            {
                Onavg_spinChanging(value);
                ReportPropertyChanging("avg_spin");
                _avg_spin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avg_spin");
                Onavg_spinChanged();
            }
        }
        private Nullable<global::System.Decimal> _avg_spin;
        partial void Onavg_spinChanging(Nullable<global::System.Decimal> value);
        partial void Onavg_spinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avg_horz
        {
            get
            {
                return _avg_horz;
            }
            set
            {
                Onavg_horzChanging(value);
                ReportPropertyChanging("avg_horz");
                _avg_horz = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avg_horz");
                Onavg_horzChanged();
            }
        }
        private Nullable<global::System.Decimal> _avg_horz;
        partial void Onavg_horzChanging(Nullable<global::System.Decimal> value);
        partial void Onavg_horzChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avg_vert
        {
            get
            {
                return _avg_vert;
            }
            set
            {
                Onavg_vertChanging(value);
                ReportPropertyChanging("avg_vert");
                _avg_vert = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avg_vert");
                Onavg_vertChanged();
            }
        }
        private Nullable<global::System.Decimal> _avg_vert;
        partial void Onavg_vertChanging(Nullable<global::System.Decimal> value);
        partial void Onavg_vertChanged();

        #endregion
    
    }

    #endregion
    
}
